name: Unit Tests

on:
  pull_request:
    branches: [develop,main]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.25.1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...
